# .github/workflows/deploy.yml
name: Deploy to VPS

on:
  push:
    branches:
      - main # Или другая ветка, которую вы используете для деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Копируем Caddyfile и docker-compose.yml в корень ~/okoloapp
    - name: Copy config files to VPS
      run: |
        scp -o StrictHostKeyChecking=no Caddyfile docker-compose.yml root@46.17.44.239:/root/okoloapp/
    # Копируем содержимое frontend/ (включая index.html, app.js и т.д.) в ~/okoloapp/html/
    - name: Deploy frontend files to VPS html directory
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./frontend/ root@46.17.44.239:/root/okoloapp/html/
    # Перезапускаем контейнеры
    - name: Restart Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no root@46.17.44.239 "cd /root/okoloapp && sudo docker compose up -d"